---
application:
  name: "xaria2"
  project: "aria-rclone"
  organization: "QoveryCommunity"
  storage:
  - name: "Flint"
    size: "100"
    type: "fast_ssd"
    mount_point: "/mnt/Flint"
routers:
- name: "main-xaria2"
  routes:
  - application_name: "xaria2"
    paths:
    - "/*"
